.travis.yml, Gemfile, Jenkinsfile, Jenkinsfile_linux, Jenkinsfile_osx, Jenkinsfile_windows, build_openstudio_gems.rb, lib/rubygems_plugin.rb, openstudio-gems.gemspec
Testing new Jenkins CI job for building openstudio on 3 platforms. 
[x] Linux
[x] OSX
[x] Windows
Can merge once all 3 above are completed and pass.
=> testing jenkins CI job to build native ext

.travis.yml, Gemfile, Jenkinsfile_linux, Jenkinsfile_osx, Jenkinsfile_windows, openstudio-gems.gemspec
Replaces https://github.com/NREL/openstudio-gems/pull/10
=> Bundler bump to 2.1.x

Gemfile
Update OpenStudio Gems for standards release candidate.
=> updating openstudio_standards for 0.2.11.rc1

Gemfile, openstudio-gems.gemspec
Updating openstudio workflow gem to 2.0.0.pre1
=> Updating workflow to 2.0.0.pre1

Gemfile, openstudio-gems.gemspec
Updating gems in prep for OpenStudio 3.1.0 release.
=> Updating gems in prep for 3.1.0 release

openstudio-gems.gemspec
Changes #31. I had to push to my own fork since I don't have write access to this repo for some reason.
=> Bump workflow gem

Gemfile
updating standards to 0.2.12.rc6
=> updating standards to 0.2.12.rc6

Gemfile
Update and build gems using openstudio-standard master branch
We'll tag and release to standards official once available
=> Update and build gems using openstudio-standard master branch

Gemfile
Update openstudio standards_0.2.12.rc7
=> Update openstudio standards_0.2.12.rc7

Gemfile, openstudio-gems.gemspec
Update openstudio-ext gem to v0.3.1
=> Update openstudio-ext gem to v0.3.1

openstudio-gems.gemspec
=> Update the gem spec to 3.1.0

Gemfile, Jenkinsfile_linux, openstudio-gems.gemspec
testing out new standards release v0_2_13_rc3
=> test out standards v0_2_13_rc3

Gemfile, openstudio-gems.gemspec
Bump ext to 0.4.2 and standards to 0.2.13
=> Bump ext to 0.4.2 and standards to 0.2.13

Gemfile, openstudio-gems.gemspec
Testing new measure tester gem with updated rubocop and git versions.
=> testing new measure_tester

Gemfile, openstudio-gems.gemspec
Testing newer versions of workflow, ext and standards
=> test workflow and extension gem updates

build_openstudio_gems.rb
This is a very straightforward PR.
=> naming tar.gz for M1 (aarch64/arm64 mac)

Gemfile
Adding tbd gem https://github.com/rd2/tbd/releases/tag/v3.0.0
=> add in tbd gem v 3.0.0

Gemfile, openstudio-gems.gemspec
=> Update gems standards 0.3.0

Gemfile, openstudio-gems.gemspec
Updating to the 0.4.0 release of standards
=> Update standard 040

Gemfile
To fix https://github.com/NREL/OpenStudio/issues/4870
=> pin addressable to 2.8.1

README.md, build_openstudio_gems.rb, lib/rubygems_plugin.rb
- Companion PR: https://github.com/NREL/OpenStudio/pull/4881
=> Support 2204 arm64

Gemfile
add json_schemer 2.0.0 for:
* https://github.com/NREL/OpenStudio/issues/4969
* Companion PR: https://github.com/NREL/OpenStudio/pull/4974
@wenyikuang
=> #4969 - add json_schemer 2.0.0

Gemfile, build_openstudio_gems.rb, lib/rubygems_plugin.rb
As @brianlball aptly pointed out, now that python measures exist, it is pointless to keep pycall
=> Remove pycall

create_cmakelist_diff.py
=> Lint python

Gemfile
Track kyle's PR:
* https://github.com/NREL/OpenStudio-workflow-gem/pull/152
=> Track HEREDOC workflow PR

lib/rubygems_plugin.rb
Quite sure the first commit is right. The second one is cleaner and should work equally, but in case it doesn't we can revert
=> Json: do not export json.a as it doesn't exist

Gemfile, openstudio-gems.gemspec
@wenyikuang Will have to redo the v3.8.0 tagging anyways
=> bump 3.8.0

Gemfile
As upon Denis request, update tbd gem to 3.4.3
=> Update tbd to 3.4.3.

Gemfile
Bump openstudio-standards and openstudio-exntension to current version to be test.
=> Update os extension

openstudio-gems.gemspec
Succesfully built with my repo.
=> Update in the gemspec too
